language: common-lisp
sudo: required

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -s prove -e '(progn (ql:quickload (list :trivial-sat-solver :trivial-sat-solver-test)) (or (prove:run :trivial-sat-solver-test) (uiop:quit -1)))'